services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=django_website_template.settings
    expose:
      - "8000"  # Expose port internally for Nginx
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 django_website_template.wsgi:application"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # Keep for HTTP-to-HTTPS redirect
      - "443:443" # Map HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount certificates
    depends_on:
      - web

volumes:
  static_volume:
